Feature/memento strategy
COS214-Project-2024/CIV-0 pull request #24
Opened 2024-10-24 12:13 UTC by CaptainShayfish

2024-10-24 12:19 UTC, RaiderRoss approved these changes

2024-10-24 12:49 UTC, jacqu3sk requested changes
Please fix all the imports I have noted

2024-10-24 12:49 UTC, jacqu3sk commented on src/policies/base/Policy.h
> +#include "Memento.h"
Hey there is an import issue here can you just make sure to import "utils/Memento.h" not "Memento.h"

2024-10-24 12:49 UTC, jacqu3sk commented on tests/utils/MementoTest.cpp
> +#include "Memento.h"
Also please fix the import here it should be `#include "utils/Memento.h"` not `#include "Memento.h"`

2024-10-24 12:49 UTC, jacqu3sk commented on tests/utils/CaretakerTest.cpp
> +#include "Memento.h"
also fix the includes here to `#include "Memento.h"` should be `#include "utils/Memento.h"` and `#include "Caretaker.h"` should be `#include "utils/Caretaker.h"`

2024-10-24 12:49 UTC, jacqu3sk commented on tests/policies/water/LowWaterPolicy.cpp
> +#include "LowWaterPolicy.h"
Also fix the import here it should be #include "policies/water/LowWaterPolicy.h" and not #include "LowWaterPolicy.h"

2024-10-24 13:09 UTC, jacqu3sk requested changes
Please view all the comments I made and make the changes please

2024-10-24 13:09 UTC, jacqu3sk commented on tests/policies/base/PolicyTest.cpp
> +#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
Remove this line please

2024-10-24 13:09 UTC, jacqu3sk commented on tests/policies/electricity/HighElectricityPolicyTest.cpp
> +#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
Remove this line please

2024-10-24 13:09 UTC, jacqu3sk commented on tests/policies/electricity/LowElectricityPolicyTest.cpp
> +#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
Remove this line please

2024-10-24 13:09 UTC, jacqu3sk commented on tests/policies/electricity/NormalElectricityPolicyTest.cpp
> +#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
Remove this line please

2024-10-24 13:09 UTC, jacqu3sk commented on tests/policies/water/HighWaterPolicy.cpp
> +#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
Remove this line please

2024-10-24 13:09 UTC, jacqu3sk commented on tests/policies/water/LowWaterPolicy.cpp
> +#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
Remove this line please

2024-10-24 13:09 UTC, jacqu3sk commented on tests/policies/water/NormalWaterPolicy.cpp
> +#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
Remove this line please

2024-10-24 13:09 UTC, jacqu3sk commented on tests/utils/CaretakerTest.cpp
> +    delete m2;
Also remove these two delete lines they cause a double free error

2024-10-25 17:50 UTC, jacqu3sk requested changes

2024-10-25 17:59 UTC, jacqu3sk approved these changes
Everything looks good now

2024-10-25 20:00 UTC, RaiderRoss approved these changes

2024-10-25 20:04 UTC, merged